[project]
name = "r-packages"
version = "0.1.0"
description = "Add a short description here"
authors = ["Mikkel Roald-Arbøl <github.ggb9a@simplelogin.co>"]
channels = ["conda-forge"]
platforms = ["osx-64"]

[tasks]
rstudio = "open -a rstudio"
rproject = "open *.Rproj"

[dependencies]
bash = ">=5.2.15,<5.3"
r = ">=4.3,<5"
r-dplyr = ">=1.1.4,<1.2"
r-jsonlite = ">=1.8.8,<1.9"
rstudio-desktop = ">=2022.12.0,<2022.13"
